# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a644e8718ad852d51fac3064443937085d6dcacc0507419fec639fff78d9db900e7f894e72b036463117cd1b7d3d6e07be216fb9da0e19eae6844d5e689986b1

test:
  secret_key_base: 6a9100c38b6255aa16b6a3bace45a190624fc72acb154a3dd90f3ecf372708915261d4e36888f5fdb516ff529ab6335d93b2a597e89a88f39df55e280a50fc8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
